In [91]:
import numpy as np
import pandas as pd

In [92]:
rot_path= "rotation_matrices/"
error_path="errors/"
names = ["andreadm2.ply", "iacopo2.ply", "subject002.ply", "subject003.ply", "subject004.ply", "subject005.ply", "subject006.ply", "subject007.ply", "subject008.ply", "subject010.ply","subject011.ply", "subject012.ply", "subject013.ply", "subject014.ply","subject015.ply", "subject016.ply", "subject017.ply", "subject018.ply", "subject019.ply", "subject020.ply"]

In [117]:
filenames = []
evs = np.zeros(361)
every=[]

for i in names:
    for j in names:
        filename=(error_path+i+"_"+j+".txt")
        file = open(filename, "r")
        count=1
        errs=0
        iters =0
        category =0
        compares=(i+" - "+ j)
        
        
        if(j==i):
            equal = 1
        else:
            equal =0  
            
            
        for line in file:
            if(count==1):
                tmp = float(line)
                iters=int(tmp)
            if(count==2):
                errs = float(line)
            if(count==3):
                tmp2 = float(line)
                category = int(tmp2)
                #category=float(line)
            count=count +1
        filenames.append(filename)
        tmp=np.array([iters, errs, category, equal, compares])
        every.append(tmp)
        
        
complete = np.asarray(every)

In [118]:
data = pd.DataFrame({'Iterations': complete[:, 0], 'Error': complete[:, 1], 'Category': complete[:,2], 'Same_face': complete[:,3], 'Compares': complete[:,4]})

data = data.astype({"Iterations": int, "Error": float, 'Category': int, 'Same_face': int, 'Compares': str})

#df2 = data.groupby('Same_face')
#df2['Category']


data.groupby('Category').count()

          Iterations  Error  Same_face  Compares
Category
1                135    135        135       135
2                213    213        213       213
3                 52     52         52        52

In [119]:
#Rotation matrix to numpy arrays
test = []
tmp4=[]
tmp5=[]
for i in names:
    for j in names:    
        guess_name =i+"_"+j+"_guess.txt"
        init_name=i+"_"+j+"_initial.txt"
        guess_file = open(rot_path+guess_name, "r")
        init_file= open(rot_path+init_name, "r")
        counter = 0
        test=[]
        for line in guess_file:
            tmp = line.rstrip()
            row = tmp.split(",")
            r =  np.array(row, dtype = float)
            counter=counter+1
            test.append(r)
        guess_matrix=np.array(test)
        #print(guess_matrix)
        tmp4.append(guess_matrix)
        test=[]
        for line in init_file:
            tmp = line.rstrip()
            row = tmp.split(",")
            r =  np.array(row, dtype = float)
            counter=counter+1
            test.append(r)
        init_matrix=np.array(test)
        tmp5.append(init_matrix)        
        

initials = np.asarray(tmp5)
guesses =np.asarray(tmp4)

In [120]:
diffs = []
for i in range(len(initials)):
    tmp = np.abs(initials[i]-guesses[i])
    tmp2 = tmp.sum()
    diffs.append(tmp2)

#print(diffs)
for n in diffs:
    print (n)

0.0028314104519500533
1.0353940788581095
0.606115218509586
5.580482639171994
6.647262852964669
0.7336164114080124
0.5754051617289058
6.052513416608732
7.152405371045409
7.280771782623412
6.403187174725767
0.9359455925779263
6.031597521401536
5.992297820487784
0.5971776512693322
4.296611078461476
0.3909322049678548
0.9550358220678716
6.296106068579698
6.673984600680609
0.627568294952809
0.0018924050987086981
0.3264567053499452
0.6972049865671415
0.5912841398055544
0.23266934499366404
6.923947228187872
6.50109830739194
6.843987701326878
7.6795826313957
0.912234896594945
0.2249547030945877
5.740863583153271
7.08713289339599
0.3001276656587939
7.148463690393876
0.40321726680705167
0.3402509097087027
7.372600448849097
0.18127297981584123
0.2941189567602105
0.287127299802457
0.00038945352079167855
0.3301682637711991
0.24781009021575684
0.12163351121223745
6.122534533003042
6.7293949028096005
7.556131650160849
6.29118810116301
6.855145566509475
0.18116843574838956
6.771015201699459
7.380122683930634
0.10183192794363227
3.8403360103621953
0.11397291558746848
0.12413863773162476
5.490218100601046
5.388210230134469
0.37506890274274124
0.44327625989709046
0.3177407629798985
0.00164449986315314
0.16698108235842482
0.3765279168264768
5.428764676354308
6.587998423081802
5.613424134131041
6.23994034060098
6.294773323347672
0.3712974342762764
1.6162815566425888
7.030557176151105
0.17839161661500536
6.838835081409272
0.3704227201954089
0.38375308037118866
6.960903916524983
6.872722859946316
5.939494490660987
2.000542122156387
3.8213350866159774
2.457087596923835
0.0025450037643718615
0.3078894782363806
0.3997279049239249
0.3256211098909803
6.957723245459439
6.558666533174956
6.43727807170354
6.993721998015955
5.910643015807496
0.23714657385860438
0.24854487898652863
0.638255374698969
5.876671311097648
7.131901170430516
6.006521302982042
0.3447094451079617
0.7037167615378042
0.32710956791283036
0.2514109768852119
0.47477981673424197
0.6269514077198952
0.0018156314814044006
5.84413401254522
0.5427814661190719
6.110657740826783
6.067197491247164
7.3829565342558725
0.294434469420611
7.308146189331091
6.89985352099235
0.20561379769232874
5.180262525980542
0.16963590197970155
0.19552924514314254
7.004906673578732
5.819904575296459
6.226050205570362
0.48570509137938744
0.7176692108771995
0.37370069368812636
0.9117808462005197
0.5341652361870178
0.0023459169001917093
0.6101905867209951
6.93692551248667
0.2379504096361572
6.534837526259812
4.367600727462739
6.843054841496723
0.22886873692091447
6.842884725230392
0.10614140380291602
1.7598813591285014
0.22123864952704522
7.025152078829586
0.25300270754580945
5.793269644044731
2.6035295085409618
1.5888164715306372
0.22620287242959203
0.30106934423065246
1.6608418184984661
0.3450797115081123
0.0035895970532343058
7.643309272141934
0.33352307627063016
0.9615585568316175
0.3300602358616088
5.198380608335827
0.3539338976613322
0.24774156972327663
0.4577693837318281
0.502476572910687
0.3171961126594298
5.885647583602155
0.45202557843422014
7.098192914696128
6.504952837957692
6.7997347077710515
6.981573207671616
6.170960033078919
6.111776029544431
0.4870660322404503
0.7271238875959358
0.002469485134999172
0.624277228251754
3.1440485897147523
7.289684017360813
6.481098515420466
0.3363625093918339
6.958400571758836
6.949986289912637
7.230718324406432
7.1478889461670825
0.39320895319040616
0.33057625422830017
6.773204690614273
5.790982056460658
6.658050685896579
6.23160418052252
6.441997134673044
2.0200138353891495
0.202442814968489
0.2989653321550404
7.219891587148368
0.002887119041265311
6.909408209414534
5.46354892236687
6.288745207400746
0.1837424712411606
6.973110098202301
0.13419803688860066
7.259975164258476
6.906346171688934
0.23851285262702193
0.32209871927436473
5.659019382322925
7.239344760418445
6.980009393496649
6.388447197281037
6.913722575547
6.3923587329467075
0.45422424711257586
2.724847113154994
0.46729308853295576
7.190047486018584
0.003971858188454178
7.3268914719688265
0.23970573633186837
7.217843645893358
6.670617066046271
3.5663254389301393
6.808273369556996
6.904535170538494
0.5040775279618417
6.749236769516723
0.4474032636405091
0.08184380241423413
0.10503620012546777
0.33957562906405553
0.4212392149601915
0.10726015035081622
7.361836948612418
5.315863147138298
6.3063679357735465
1.0888904050577475
6.7892430495348
0.0020927790143239478
7.4736231580250765
6.47253456600545
0.19788173140408155
5.842557797154198
0.238254300695947
0.07041517030784153
6.399794505462609
3.4444794335104767
6.612068821465737
7.386422110072949
0.4529844775865509
1.0651470585613547
0.39183685070512664
6.454016203992038
7.277474578966009
6.884551482070281
6.619538919844368
7.4170413392306855
0.49805561111075725
1.8667655172526163
0.002223825744250868
6.771293199663222
0.1297803246708216
6.843647225835698
7.120370954155791
0.17567154550720884
7.066032696002548
5.709575520672386
6.158500692925676
4.558005818678419
0.21647185382489043
5.740681566989959
0.3365374739394622
3.857781396451476
0.1553506207292718
0.38817827051164533
6.3256109390142665
0.18626190273710924
0.2656050117935036
2.221056923719561
6.813200204671048
0.0015616850699989582
6.092236519979846
0.010369770549337076
5.001800396334846
3.4329110483405123
0.052174385035613904
0.3587288618645564
0.2802526894654378
0.4566281828499288
0.14452329642909734
0.26599341389401776
0.2816319103216907
0.21353936425559758
7.2662282846772355
7.287078221404297
6.760843238095936
6.396629573078845
0.2929792763934721
0.2994056366895814
5.438368952880888
6.166613246082967
0.0021120174939586837
6.949584470811247
0.17931953357087163
0.2358366983982196
7.139073034065547
6.513797013799388
0.3214881635856705
4.284119065288652
0.3689689416244402
0.29723057236853434
5.78301859143127
0.251970853274364
0.3590837500426188
0.20884241468299586
0.44099886174673497
0.13498074977405586
6.850568505485771
4.979579246965251
6.617268770695539
0.2312512647003571
0.15477763818955895
0.0035235061364970455
0.1465126468029639
5.90350672248832
6.376286856272404
6.5873121710235
0.3206022479235271
0.4480044426289629
0.32555905360044934
0.3269562794107686
0.4280735505840298
0.2657124519679037
6.528288449010439
0.36030886962497805
6.682569888561417
5.912081449851021
0.36945121829337835
0.3805465844122945
5.763317749177068
2.4909576964815527
0.15278310707652976
5.112852312334531
0.002809276088933804
0.26739800769903727
6.292360568852652
7.175771734849913
0.2575241138080647
0.19784431052782697
0.08666445580746313
0.28194169014937026
0.33353314521513944
0.09891641036465848
7.463600821600722
4.291376718147511
7.564280814034129
7.716557487715454
5.887986400391152
0.14332337208408447
4.005098103561159
6.90526763938864
0.17935859639637103
0.8065406422259549
0.28582211458038304
0.0027382014677324595
6.343943545370003
6.57643156638843
6.9714213696645775
6.541901993474907
7.189452162839406
6.964885082077805
6.601642675516219
5.423714934950357
0.3059586834629518
0.2845804706544276
0.39591082568918345
0.10872828106127794
2.121922521432046
6.61006841577224
4.714330021507411
4.291258502832657
7.177126399411433
6.72118253620509
7.056960762917927
6.977313807585844
0.0017389994109373585
2.8363838528718923
0.37743466705880324
3.2321698795380227
4.9309336993451245
1.5761493365835455
2.9251587440181943
5.272658586782094
0.2754132223904269
0.5509938197123865
0.252034265839009
0.342028184827537
6.279903365103221
2.4849496792639
7.266930235191998
0.28626077888871293
5.746164815146497
0.2930602203225318
5.673564315964921
5.483283242115851
6.953363476822233
0.0020962657236288512

In [121]:
data['Matrix difference'] = diffs

In [122]:
data.describe()

       Iterations       Error    Category   Same_face  Matrix difference
count  400.000000  400.000000  400.000000  400.000000         400.000000
mean    51.405000    9.943400    1.792500    0.050000           3.282069
std     38.901984    6.600949    0.652309    0.218218           3.033283
min      1.000000    1.757949    1.000000    0.000000           0.000389
25%     14.750000    5.185008    1.000000    0.000000           0.299947
50%     36.500000    8.228317    2.000000    0.000000           2.171490
75%     99.000000   11.930538    2.000000    0.000000           6.529926
max     99.000000   32.932870    3.000000    1.000000           7.716557

In [125]:
#data.groupby('Category').count()

#same = data.loc[(data['Category'] == 3) & (data['Same_face']==0)]
same = data.loc[data['Same_face'] == 1]
same.groupby('Category').count()

          Iterations  Error  Same_face  Compares  Matrix difference
Category
3                 20     20         20        20                 20

In [129]:
same
#Where error < 3 put in third category
#Make confusion matrix
#Write stuff in presentation
#Read open3d

,Iterations,Error,Category,Same_face,Compares,Matrix difference
0,1,2.120494,3,1,andreadm2.ply - andreadm2.ply,0.002831
21,1,2.011213,3,1,iacopo2.ply - iacopo2.ply,0.001892
42,1,1.887480,3,1,subject002.ply - subject002.ply,0.000389
63,1,1.856618,3,1,subject003.ply - subject003.ply,0.001644
84,1,1.932247,3,1,subject004.ply - subject004.ply,0.002545
105,1,2.009399,3,1,subject005.ply - subject005.ply,0.001816
126,1,1.825287,3,1,subject006.ply - subject006.ply,0.002346
147,1,1.851361,3,1,subject007.ply - subject007.ply,0.003590
168,1,1.987864,3,1,subject008.ply - subject008.ply,0.002469
189,1,1.853112,3,1,subject010.ply - subject010.ply,0.002887
210,1,1.757949,3,1,subject011.ply - subject011.ply,0.003972
231,1,1.871470,3,1,subject012.ply - subject012.ply,0.002093
252,1,1.903708,3,1,subject013.ply - subject013.ply,0.002224
273,1,1.955982,3,1,subject014.ply - subject014.ply,0.001562
294,1,2.038683,3,1,subject015.ply - subject015.ply,0.002112
315,1,2.018513,3,1,subject016.ply - subject016.ply,0.003524
336,1,1.980727,3,1,subject017.ply - subject017.ply,0.002809
357,1,1.899455,3,1,subject018.ply - subject018.ply,0.002738
378,1,2.023947,3,1,subject019.ply - subject019.ply,0.001739
399,1,1.922146,3,1,subject020.ply - subject020.ply,0.002096